apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xo7jp17j1-go
  janus-idp.io/tekton: xo7jp17j1-go
  backstage.io/kubernetes-id: xo7jp17j1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xo7jp17j1-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
