apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xo7jp17j1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xo7jp17j1-go 
  name: xo7jp17j1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xo7jp17j1-go 
